/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.Wallet;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-02-20T21:59:16.206Z")

@Api(value = "cash", description = "the cash API")
@RequestMapping(value = "")
public interface CashApi {

    @ApiOperation(value = "", nickname = "cash", notes = "Exchange provided treasure for money.", response = Wallet.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Payment for treasure.", response = Wallet.class),
        @ApiResponse(code = 200, message = "- 409.1003: treasure is not digged ", response = Error.class) })
    @RequestMapping(value = "/cash",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Wallet> cash(@ApiParam(value = "Treasure for exchange." ,required=true )  @Valid @RequestBody String args);

}
