/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Dig;
import io.swagger.model.Error;
import io.swagger.model.TreasureList;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-02-20T21:59:16.206Z")

@Api(value = "dig", description = "the dig API")
@RequestMapping(value = "")
public interface DigApi {

    @ApiOperation(value = "", nickname = "dig", notes = "Dig at given point and depth, returns found treasures.", response = TreasureList.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of treasures found.", response = TreasureList.class),
        @ApiResponse(code = 200, message = "- 422.1000: wrong coordinates - 422.1001: wrong depth ", response = Error.class) })
    @RequestMapping(value = "/dig",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<TreasureList> dig(@ApiParam(value = "License, place and depth to dig." ,required=true )  @Valid @RequestBody Dig args);

}
